"""initial_schema

Revision ID: 47c3df382586
Revises: 
Create Date: 2026-05-08 11:35:51.159443

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '47c3df382586'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
